### ISSUE TITLE
Already logged in as an other user

### ISSUE THREAD

**Issue by psren** [aryehraber/statamic-impersonator#1]
I want to impersonate a user, but I'm getting this error.

<img width="926" alt="bildschirmfoto 2018-06-09 um 16 43 08" src="https://user-images.githubusercontent.com/1016798/41192813-4660cc00-6c04-11e8-9993-bc32e9223c7b.png">

<img width="832" alt="bildschirmfoto 2018-06-09 um 16 43 03" src="https://user-images.githubusercontent.com/1016798/41192814-4bd85b1c-6c04-11e8-9081-a13d2dc746b8.png">

**Comment by aryehraber** [comment]
Hi @psren, thanks for the bug report.

Just released a fix for this, as well as some other minor improvements to go with Statamic v2.9: https://github.com/aryehraber/statamic-impersonator/releases/tag/v1.1

Closing for now, but feel free to re-open if you continue having issues after re-installing the latest version. Thanks!

**Comment by psren** [comment]
Hey @aryehraber thanks for the super quick release.
Impersonation now works like expected.

But I'm not able to stop the impersonation.
Maybe just too stupid to find the button?!

**Comment by aryehraber** [comment]
@psren The UI improvements (incl. the button to stop the impersonation) now require Statamic v2.9 as the gents made some changes to how the CP looks/works.

Which version are you using atm?

**Comment by aryehraber** [comment]
This is where the button is now located:

<img width="1203" alt="screen shot 2018-06-10 at 18 59 35" src="https://user-images.githubusercontent.com/5065331/41204111-9e3529d0-6ce0-11e8-83c3-f3e6f7c2bee6.png">

**Comment by psren** [comment]
I'm on 2.9.8.
Cleaning the browser-cache did the trick, because the old file was different.

Sorry for that :-)

**Comment by aryehraber** [comment]
No worries, thanks for confirming it works 😊
