### ISSUE TITLE
admins/users - if usage allowed - can level themselves up to Super Admins

### ISSUE THREAD

**Issue by michapixel** [aryehraber/statamic-impersonator#14]
can this be tricked somehow, so that one specific user can only impersonate one group/role or specific users?

**Comment by aryehraber** [comment]
Hi @michapixel, no this isn't currently possible but sounds like a great Feature Request!

I'm open to a PR, otherwise I'll try and find some time for this (might take a while). Thanks!

**Comment by michapixel** [comment]
Ahem, this is currently possible but i think it shouldn't be.

This is somehow related to the other post i did today.

Aryeh Raber ***@***.***> schrieb am Fr., 10. Sept. 2021,
17:34:

**Comment by aryehraber** [comment]
I was referring to "specific user can only impersonate one group/role or specific users" which I don't think is currently possible. 

Regarding the issue of a user upgrading themselves to another role, yes this is possible and therefore (at the moment) only top-level users should have the ability to impersonate, basically just Super Admins to help debug issues.
