### ISSUE TITLE
Impersonator no longer seems to work

### ISSUE THREAD

**Issue by mikemartin** [aryehraber/statamic-impersonator#20]
Hey @aryehraber 

I don't see anything in the error logs, but when I run the impersonation action from the "Start Impersonation" dropdown item on a user I get a success message but nothing happens. I suspect this could be related to using the new MemberBox addon but I'm not positive.

<img width="353" alt="Screen Shot 2021-12-23 at 2 46 09 pm" src="https://user-images.githubusercontent.com/414211/147185149-35191a3a-a2ee-4a84-a208-46c154acdd49.png">

**Comment by aryehraber** [comment]
Sorry about this one, I missed a few class references in my previous changes. Fixed in `v2.4.1`!
