### ISSUE TITLE
Impersonate/terminate without updating last login date

### ISSUE THREAD

**Issue by jacksleight** [aryehraber/statamic-impersonator#24]
When you impersonate a user it would be great if it could leave the last login date unchanged, so it still reflects when that person actually logged in themselves.

I have an implementation of this working, by suppressing the login event so that the `SetLastLoginTimestamp` listener is never called. This uses [exactly the same approach](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L399-L414) as Laravel's `saveQuietly` method for Eloquent models.

Would you be open to a PR to add this?

I'm assuming the current behaviour is intended, in which case this would probably need to be configurable via some kind of `fire_auth_events => true/false` opt-in. Unless you might consider the current behaviour a bug?

**Comment by aryehraber** [comment]
Hey @jacksleight, that sounds great actually! Will happily review and merge a PR 👍
