### ISSUE TITLE
Impersonator screen is broken in v3 with Eloquent users

### ISSUE THREAD

**Issue by damcclean** [aryehraber/statamic-impersonator#3]
I've just installed the addon in one of my v3 sites that happens to use Eloquent for storing users.

The install worked fine. However when I went to view the impersonator view, I got an error: `Call to undefined method App\User::id()`

![image](https://user-images.githubusercontent.com/19637309/78153664-36d05b00-7433-11ea-9e4d-4f6d90b6b2af.png)

Looks like it's coming from Line 17 on the ImpersonationController where it references the user's id. 

It's getting the ID from a method, that method doesn't exist but if you remove the parenthesis and get it as data, it works.

I would submit a pull request but I'm not too sure if this would then break the addon for apps that use flat files for users.

**Comment by aryehraber** [comment]
Hey @damcclean, thanks for submitting this issue!

Hmm yeah, removing that would break the functionality for Statamic's file-based users I think... Will setup an Eloquent-based {{S}} site locally and give it a test. Thanks!

**Comment by damcclean** [comment]
Awesome!

I've managed to get it setup after changing references to it locally.

**Comment by aryehraber** [comment]
Fixed in latest commit! Please re-open and let me know if you still have issues.

**Comment by aryehraber** [comment]
p.s. You should just be able to run `composer update aryehraber/statamic-impersonator` (after discarding your local changes)

**Comment by damcclean** [comment]
Yup, that does it! Thanks for your quick work 😄
