### ISSUE TITLE
v3: Option to configure where to redirect user when starting impersonation

### ISSUE THREAD

**Issue by damcclean** [aryehraber/statamic-impersonator#4]
A bit of context of how I'm using the addon: I run a Saas app built on Laravel and I use Statamic as my admin panel and CMS.

Right now when I start impersonation, I receive two toast messages: one saying impersonation has started, and one saying 'Unauthorised' because my Saas users can't access the Statamic CP.

![image](https://user-images.githubusercontent.com/19637309/84710885-017cd900-af5d-11ea-91ea-ef02dc7675b8.png)

Instead of staying on the same page and getting the 'Unauthorised' error, I'd like for the impersonation to start at `/app/home` or whatever so I don't need to change URL.

**Comment by aryehraber** [comment]
Hey @damcclean, thanks for the request! 

The addon currently checks if the user has CP access and redirects accordingly: https://github.com/aryehraber/statamic-impersonator/blob/statamic-3/src/ImpersonatorAction.php#L50 -- but making this configurable sounds like a good way to go 👍 

Will try get this up later this week!

**Comment by aryehraber** [comment]
Wanted to patch this up for you tonight, but I've hit an issue with Statamic's Action Redirects. Need to dive in a little deeper and submit an Issue/PR so might take a little longer. 

Question: are you starting impersonation sessions via `/cp/users` or via Impersonator Utility?

**Comment by damcclean** [comment]
> Wanted to patch this up for you tonight, but I've hit an issue with Statamic's Action Redirects. Need to dive in a little deeper and submit an Issue/PR so might take a little longer.
> 
> Question: are you starting impersonation sessions via `/cp/users` or via Impersonator Utility?

No problem, that's absolutely fine. I'm starting impersonation through `/cp/users`.

**Comment by aryehraber** [comment]
This feature has been add to the latest version of the `statamic-3` branch!

Unfortunately, it won't work as expected from `/cp/users` until this Statamic bug is resolved: https://github.com/statamic/cms/issues/1946

Closing as this will start working as soon as that issue is resolved. In the meantime, you should be able to use the Impersonator Utility which will redirect as expected, granted the UI isn't great compared to the User Index view.

**Comment by damcclean** [comment]
Awesome! Thanks for the work on this one.
