### ISSUE TITLE
Internationalization gets forced to English in Statamic

### ISSUE THREAD

**Issue by jelleroorda** [aryehraber/statamic-impersonator#8]
After a lot of hours I was finally able to debug how our application 'suddenly' turned into English (for only json translations). It turns out the problem is in the lines [#40](https://github.com/aryehraber/statamic-impersonator/blob/master/src/ImpersonatorServiceProvider.php#L40) and [#42](https://github.com/aryehraber/statamic-impersonator/blob/master/src/ImpersonatorServiceProvider.php#L42) of the ImpersonatorServiceProvider.

I'm not sure if I understand why it exactly is happening, but for some reason the calls to the `__()` function are too early in the booting process. When I delay the code creating the utility like this:

```php
$this->app->booted(function() {
    Utility::make('impersonator')
        ->title(__('Impersonator'))
        ->icon('revealer')
        ->description(__('Authenticate as another user.'))
        ->routes(function (Router $router) {
            $router->get('/', [ImpersonatorController::class, 'index'])->name('index');
            $router->post('/', [ImpersonatorController::class, 'store'])->name('store');
        })
        ->register();
});
```

The CP is correctly translated in my configured language (apart from the Impersonator addon; I will still work on that one of these days).

**Comment by jelleroorda** [comment]
(For now the workaround is to disable autodiscover for this package, and then manually add it in your `config/app.php`)

**Comment by aryehraber** [comment]
Hi @jelleroorda, thanks for reporting this bug, what an odd issue! I've personally not dived into i18n within Statamic's CP so haven't come across this. 

The current setup in `ImpersonatorServiceProvider` pretty much follows the [docs](https://statamic.dev/extending/utilities#creating-a-utility), perhaps this is a deeper issue within Statamic core itself. Have you seen this happen in any other Utilities/Addons?

**Comment by jelleroorda** [comment]
I haven't seen this with any other addons. The other addons we're using don't add any utilities, but other functionality into Statamic. I'm not sure if this is a Statamic bug, or whether the Statamic docs are incorrect. The one thing I can tell is that the order of the service providers matters, and yours (through package discovery) ended up on the top of the list after the core Laravel service providers. Maybe Jason will know more; I guess it would be helpful to create an issue at the statamic/cms repository and cross reference here.

**Comment by mmodler** [comment]
Any news on this? I still get this bug with current statamic and statamic-impersonator ?

**Comment by aryehraber** [comment]
Just implemented @jelleroorda's suggestion to simply register the Utility inside the `booted` callback. I didn't have a chance to fully test since I don't have a project using another locale, so please re-open this issue if you continue seeing issues. Thanks!
